cc_library(
    name = "emulator",
    srcs = ["emulator.cc"],
    hdrs = ["emulator.h"],
    deps = [
        "//src/processor",
        # "//src/memory",
        # "//src/storage"
        "//src/logger",
    ],
    visibility = ["//visibility:public"],
)
