cc_library(
    name = "processor",
    srcs = [
        "cache.cc",
        "core.cc",
        "cpu.cc",
    ],
    hdrs = [
        "cache.h",
        "core.h",
        "cpu.h",
    ],
    deps = [
        # "//src/memory",
        # "//src/storage"
        "//src/logger",
    ],
    visibility = ["//visibility:public"],
)
